import React, { useState, useEffect } from 'react';
import Layout from '@theme/Layout';
import { useSchemaData } from '@site/src/hooks/useSchemaData';
import SchemaNavigator from '@site/src/components/SchemaNavigator';
import DatasetView from '@site/src/components/DatasetView';
import FieldDetail from '@site/src/components/FieldDetail';
import styles from './schema.module.css';

export default function Schema(): JSX.Element {
  const { data, loading, error } = useSchemaData();
  const [activeDataset, setActiveDataset] = useState<string | null>(null);
  const [activeField, setActiveField] = useState<string | null>(null);
  const [searchQuery, setSearchQuery] = useState('');

  // Parse URL hash for deep linking
  useEffect(() => {
    const parseHash = () => {
      const hash = window.location.hash;
      if (hash) {
        // Format: #table~distribution_transformer or #table~distribution_transformer~field~rated_voltage
        const parts = hash.slice(1).split('~');
        if (parts[0] === 'table' && parts[1]) {
          setActiveDataset(parts[1]);
        }
        if (parts[2] === 'field' && parts[3]) {
          setActiveField(parts[3]);
        }
      }
    };

    parseHash();
    window.addEventListener('hashchange', parseHash);
    return () => window.removeEventListener('hashchange', parseHash);
  }, []);

  // Update URL hash when selection changes
  const handleSelectDataset = (datasetId: string) => {
    setActiveDataset(datasetId);
    setActiveField(null);
    window.location.hash = `table~${datasetId}`;
  };

  const handleSelectField = (fieldName: string) => {
    setActiveField(fieldName);
    if (activeDataset) {
      window.location.hash = `table~${activeDataset}~field~${fieldName}`;
    }
    // Scroll to field detail
    setTimeout(() => {
      const element = document.querySelector('[class*="fieldDetail"]');
      if (element) {
        element.scrollIntoView({ behavior: 'smooth', block: 'nearest' });
      }
    }, 100);
  };

  if (loading) {
    return (
      <Layout title="Schema Documentation">
        <div className={styles.loadingContainer}>
          <div className={styles.loader}></div>
          <p>Loading schema documentation...</p>
        </div>
      </Layout>
    );
  }

  if (error) {
    return (
      <Layout title="Schema Documentation">
        <div className={styles.errorContainer}>
          <h2>Error Loading Schema</h2>
          <p>{error.message}</p>
          <p className={styles.errorHint}>
            Make sure the schema.json file has been generated by running:
            <code>python3 tools/extract_schema.py</code>
          </p>
        </div>
      </Layout>
    );
  }

  if (!data) {
    return (
      <Layout title="Schema Documentation">
        <div className={styles.errorContainer}>
          <h2>No Schema Data Available</h2>
          <p>Please generate the schema documentation first.</p>
        </div>
      </Layout>
    );
  }

  const currentDataset = data.datasets.find(d => d.id === activeDataset);
  const currentField = currentDataset?.fields.find(f => f.name === activeField);

  return (
    <Layout
      title="Schema Documentation"
      description="Comprehensive schema documentation for Grid-Data-Models">
      <div className={styles.schemaLayout}>
        <SchemaNavigator
          datasets={data.datasets}
          activeDataset={activeDataset || undefined}
          onSelectDataset={handleSelectDataset}
          searchQuery={searchQuery}
        />
        
        <main className={styles.mainContent}>
          <div className={styles.searchBar}>
            <input
              type="text"
              placeholder="Search datasets..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className={styles.searchInput}
            />
            <div className={styles.schemaInfo}>
              {data.dataset_count} datasets • {data.datasets.reduce((sum, d) => sum + d.field_count, 0)} fields
            </div>
          </div>

          {!currentDataset && (
            <div className={styles.welcomeMessage}>
              <h1 className={styles.welcomeTitle}>Schema Documentation</h1>
              <p className={styles.welcomeText}>
                Welcome to the Grid-Data-Models schema documentation. This interactive reference
                provides detailed information about all {data.dataset_count} datasets, their fields,
                types, constraints, and descriptions.
              </p>
              <div className={styles.features}>
                <div className={styles.feature}>
                  <div className={styles.featureIcon}>📋</div>
                  <h3>Browse Datasets</h3>
                  <p>Explore {data.dataset_count} tables organized by category</p>
                </div>
                <div className={styles.feature}>
                  <div className={styles.featureIcon}>🔍</div>
                  <h3>Search & Filter</h3>
                  <p>Quickly find datasets and fields using the search bar</p>
                </div>
                <div className={styles.feature}>
                  <div className={styles.featureIcon}>🔗</div>
                  <h3>Deep Linking</h3>
                  <p>Share direct links to specific tables and fields</p>
                </div>
              </div>
              <p className={styles.getStarted}>
                Select a dataset from the sidebar to get started →
              </p>
            </div>
          )}

          {currentDataset && (
            <>
              <DatasetView
                dataset={currentDataset}
                activeField={activeField || undefined}
                onSelectField={handleSelectField}
              />
              
              {currentField && (
                <FieldDetail
                  field={currentField}
                  onClose={() => setActiveField(null)}
                />
              )}
            </>
          )}
        </main>
      </div>
    </Layout>
  );
}
